### PR TITLE
env: sort environment variables

### PR DESCRIPTION
**Pull request by aboyett**
sorting the vars makes it much easier to find what you need

---
This change is [Reviewable](https://reviewable.io/reviews/aboyett/drone-env-info/1)

### CODE REVIEW

**Comment by aboyett** [comment]
@jkleckner @joseph-shidler would you mind checking out this review on reviewable?

**Comment by aboyett** [comment]
test to see if this pings github users. @jkleckner @joseph-shidler 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/aboyett/drone-env-info/1#-:-Ku7BQkkE2QY6FKBTZY0:b-ev611k)*

**Comment by joseph-shidler** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/aboyett/drone-env-info/1#-:-Ku7FsKxIMq0Cf1cIJKQ:bnfp4nl)*

**Comment by jkleckner** [comment]
LGTM

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/aboyett/drone-env-info/1#-:-KuHNzgYn3TEG7yKLmgF:bb6ywmx)*

**Comment by jkleckner** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/aboyett/drone-env-info/1)*

**Pull request merged**
